packages:
  - apps/*
  - packages/*
allowBuilds:
  '@tsparticles/engine': set this to true or false
  esbuild: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/vite-plugin@1.54.10'
  - '@cloudflare/workers-types@5.20260916.1'
  - '@types/node@22.20.3'
  - '@vitejs/plugin-rsc@0.5.35'
  - miniflare@5.20260915.0-alpha
  - wrangler@4.132.0
  - framer-motion@13.4.0
  - motion@13.4.0
